### ISSUE TITLE
Issue on page /Setup.html Step 10

### ISSUE THREAD

**Issue by CathiZeil** [pytti-tools/pytti-book#22]
In step 10 of the setup it says to clone the dev branch of the pytti-core module, but there seems to be no dev branch. 

    $ git clone --recurse-submodules -j8 --branch dev https://github.com/pytti-tools/pytti-core
    Cloning into 'pytti-core'...
    fatal: Remote branch dev not found in upstream origin

If I clone without specifying the branch I'm missing the config, images_out and pretrained folder in comparison to the folder structure given under Step 10.

**Comment by dmarx** [comment]
thanks, I definitely need to update this! you don't need to specify a branch. you can initialize the config folder by running `python -m pytti.warmup`

thanks again, tagging this as a bug for now and will close after I've updated the setup instructions

**Comment by dmarx** [comment]
ok, updated the setup instructions. lemme know what you think! https://pytti-tools.github.io/pytti-book/Setup.html

**Comment by CathiZeil** [comment]
Thanks, setup instructions work for me now
